/**
 * Central icon module. Import icons from "@/components/icons", not from
 * "lucide-react" directly — keeps usage consistent and swappable.
 */
export type { LucideIcon, LucideProps } from "lucide-react";

export {
  // Brand / AI
  Sparkles as AiIcon,
  Sparkles,
  Wand2,
  Bot,
  // Navigation (mirrors constants/navigation.ts)
  LayoutDashboard,
  Briefcase,
  ClipboardList,
  Building2,
  FileUser,
  Workflow,
  ChartColumn,
  Settings,
  // Chrome & actions
  Menu,
  PanelLeft,
  Search,
  Bell,
  Inbox,
  Plus,
  Pencil,
  Trash2,
  Copy,
  Download,
  Upload,
  ExternalLink,
  Filter,
  RefreshCw,
  MoreHorizontal,
  MoreVertical,
  // Chevrons & arrows
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  // Status & feedback
  Check,
  CheckCircle2,
  CircleAlert,
  CircleX,
  Info,
  TriangleAlert,
  Loader2 as LoaderIcon,
  Clock,
  CalendarDays,
  // Auth & user
  User,
  Users,
  LogOut,
  Eye,
  EyeOff,
  Lock,
  Mail,
  Link as LinkIcon,
  Globe,
  // Content
  FileText,
  Paperclip,
  Star,
  Bookmark,
  BookmarkCheck,
  MapPin,
  DollarSign,
  X,
  // Dashboard & insights
  Zap,
  Send,
  Target,
  TrendingUp,
  Lightbulb,
  // Jobs module
  LayoutGrid,
  List,
  SlidersHorizontal,
  BadgeCheck,
  Flame,
  Banknote,
  // Applications module
  Phone,
  Video,
  Handshake,
  Code2,
  Minus,
  FileUp,
  NotebookPen,
  MessageSquare,
  CalendarClock,
  // Resume module
  History,
  LayoutTemplate,
  ScanSearch,
  GitCompareArrows,
  GraduationCap,
  FolderGit2,
  Award,
  BriefcaseBusiness,
  // Automation module
  Play,
  Pause,
  Activity,
  Plug,
  Unplug,
  Terminal,
  Radar,
  Repeat,
  // Settings module
  CreditCard,
  GripVertical,
  Smartphone,
  Laptop,
  ShieldCheck,
  KeyRound,
  Camera,
  // Companies module
  Newspaper,
  Rocket,
  ThumbsUp,
  ThumbsDown,
  UserPlus,
  UserCheck,
  // Theme
  Sun,
  Moon,
  Monitor,
} from "lucide-react";
